import {describe,it,expect} from 'vitest';
import {DraftController} from './draft.js';
import {ClientMessageSchema} from './index.js';
describe('isolated editable drafts',()=>{
 it('preserves independent documents and undo history per session',()=>{const d=new DraftController();d.select('a');d.append('JavaScript');d.edit('这里是 TypeScript，不是 JavaScript');d.select('b');expect(d.state.text).toBe('');d.append('second');d.select('a');expect(d.state.text).toBe('TypeScript');d.undo();expect(d.state.text).toBe('JavaScript');d.redo();expect(d.state.text).toBe('TypeScript');d.select('b');expect(d.state.text).toBe('second');});
 it('refuses ambiguous replacements and rejects stale changes',()=>{const d=new DraftController();d.append('foo foo');expect(()=>d.edit('把 foo 改成 bar')).toThrow('多处');expect(d.state.text).toBe('foo foo');const rev=d.state.revision;d.append('next');expect(()=>d.update('late',rev)).toThrow('变化');});
 it('undoes utterances and edits without sending anything',()=>{const d=new DraftController();d.append('first');d.append('second');d.edit('撤销刚才一句');expect(d.state.text).toBe('first');d.undo();expect(d.state.text).toBe('first\nsecond');d.edit('把最后一句删掉');expect(d.state.text).toBe('first');});
 it('checkpoints uncertain sends and survives process restart',async()=>{const d=new DraftController();d.select('a');d.append('task');let snapshot:unknown;await expect(d.submit('req','a',d.state.revision,async()=>{throw Error('disconnected');},()=>{snapshot=d.export();})).rejects.toThrow();const restored=new DraftController();restored.import(snapshot);restored.select('a');expect(restored.state.text).toBe('task');expect(await restored.submit('req','a',restored.state.revision,async()=>{throw Error('must never retry');})).toBe(false);});
 it('retains the other session during an in-flight submission',async()=>{const d=new DraftController();d.select('a');d.append('a');let finish!:()=>void;const pending=d.submit('1','a',d.state.revision,()=>new Promise(r=>finish=r));d.select('b');d.append('b');finish();await pending;expect(d.state.text).toBe('b');d.select('a');expect(d.state.text).toBe('');});
});
it('negotiates legacy and enhanced clients and validates feature actions',()=>{const id='62dc932b-c78c-4e1e-845b-f9ddac1ebc5d';expect(ClientMessageSchema.parse({id,type:'hello',payload:{token:'a'.repeat(32),version:1,capabilities:['v2']}}).type).toBe('hello');expect(ClientMessageSchema.safeParse({id,type:'feature',payload:{action:'run-shell',text:'echo bad'}}).success).toBe(false);});
it('restores an orphaned saved draft into an empty new session without losing another draft',()=>{const d=new DraftController();d.select('old');d.append('recovered');const snapshot=d.export();const fresh=new DraftController();fresh.import(snapshot);fresh.select('new');expect(fresh.saved()[0].id).toBe('old');fresh.recover('old');expect(fresh.state.text).toBe('recovered');expect(fresh.saved()).toEqual([]);expect(()=>fresh.recover('new')).toThrow('同一个');});
