import {it,expect} from 'vitest';
import {PassThrough,Writable} from 'node:stream';
import {EventEmitter} from 'node:events';
import type {ChildProcessWithoutNullStreams} from 'node:child_process';
import {CodexAgent} from './agent.js';
function harness(){const child=new EventEmitter() as any;const sent:any[]=[];child.stdout=new PassThrough();child.stderr=new PassThrough();child.kill=()=>child.emit('exit',0);child.stdin=new Writable({write(chunk,_encoding,done){const m=JSON.parse(chunk.toString());sent.push(m);if(m.method==='initialize'||m.method==='thread/start'||m.method==='turn/start')queueMicrotask(()=>child.stdout.write(JSON.stringify({id:m.id,result:m.method==='thread/start'?{thread:{id:'thread'}}:m.method==='turn/start'?{turn:{id:'turn'}}:{}})+'\n'));done();}});const agent=new CodexAgent({id:'session',name:'test',environment:'powershell',agent:'codex',cwd:'/tmp',alive:true},false,child as ChildProcessWithoutNullStreams);return {agent,sent,event:(m:unknown)=>child.stdout.write(JSON.stringify(m)+'\n')};}
it('uses structured completion and never treats silence or a process exit as success',async()=>{const h=harness();const statuses:string[]=[];h.agent.on('status',s=>statuses.push(s));await h.agent.ready;await h.agent.submit('hello',[]);expect(statuses.at(-1)).toBe('running');h.event({method:'turn/completed',params:{turn:{id:'turn',status:'interrupted'}}});expect(statuses.at(-1)).toBe('interrupted');expect(statuses).not.toContain('completed');h.agent.close();});
it('keeps approvals pending until an explicit valid decision',async()=>{const h=harness();await h.agent.ready;h.event({id:42,method:'item/commandExecution/requestApproval',params:{threadId:'thread',turnId:'turn',command:'test'}});expect(h.agent.requests.size).toBe(1);expect(h.sent.some(m=>m.id===42)).toBe(false);expect(()=>h.agent.respond('42','always')).toThrow();h.agent.respond('42','decline');expect(h.sent.at(-1)).toEqual({id:42,result:{decision:'decline'}});expect(h.agent.requests.size).toBe(0);h.agent.close();});
it('preserves local image input and propagates a failed turn',async()=>{const h=harness();await h.agent.ready;await h.agent.submit('explain',[{id:'image',name:'error',path:'/tmp/image.png',preview:'',bytes:10,sha256:'abc'}]);expect(h.sent.find(m=>m.method==='turn/start').params.input).toContainEqual({type:'localImage',path:'/tmp/image.png'});let status='';h.agent.on('status',s=>status=s);h.event({method:'turn/completed',params:{turn:{status:'failed',error:{message:'model failed'}}}});expect(status).toBe('failed');h.agent.close();});
