const $=id=>document.getElementById(id),api=window.qube;let state=null,selected=null,dirty=false,editRevision=null;let timer;
function toast(text,error=false){$('toast').textContent=text;$('toast').className=error?'error':'';clearTimeout(timer);timer=setTimeout(()=>$('toast').className='hidden',6000);}
async function call(name,arg){try{return await api.invoke(name,arg);}catch(e){toast(e.message.replace(/^Error invoking remote method '[^']+': (?:Error: )?/,''),true);throw e;}}
function safe(action){return (...args)=>Promise.resolve().then(()=>action(...args)).catch(()=>{});}
const term=new Terminal({theme:{background:'#131e29',foreground:'#d5e6ed',cursor:'#73edd0'},fontSize:13,fontFamily:'Consolas, monospace',scrollback:3000});const fit=new FitAddon.FitAddon();term.loadAddon(fit);term.open($('terminal'));
term.onData(data=>{if(selected)call('terminal-input',{id:selected,data}).catch(()=>{});});
new ResizeObserver(()=>{try{fit.fit();if(selected)call('terminal-resize',{id:selected,cols:term.cols,rows:term.rows}).catch(()=>{});}catch{}}).observe($('terminal'));
api.on('terminal-output',({sessionId,data})=>{if(sessionId===selected)term.write(data);});
const headings={companion:'一起工作，也一起休息。',home:'你的桌面，多了一个伙伴。',coding:'说出想法，留在心流。',pairing:'让手机与电脑相遇。',settings:'让 Qube 适应你的习惯。'};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('hidden',x.id!==b.dataset.tab));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('heading').textContent=headings[b.dataset.tab];if(b.dataset.tab==='coding')fit.fit();if(b.dataset.tab==='pairing')pairings().catch(()=>{});};
function render(s){state=s;$('connection').textContent=s.connected?'● 手机已连接':'○ 手机未连接';$('connection').className='badge'+(s.connected?' online':'');$('message').textContent=s.message;$('face').className=`face ${s.face}`;$('speech').textContent=s.speech;$('mode').textContent=s.draft.mode==='dictation'?'听写模式':'控制模式';if(!dirty){$('draft').value=s.draft.text;editRevision=s.draft.revision;}$('draft-target').textContent=`发送至：${s.sessions.find(x=>x.id===s.draft.sessionId)?.name??'请先选择会话'}`;$('submit-draft').disabled=!s.draft.confirmedConnection||(!s.draft.text.trim()&&!s.draft.attachments?.length)||dirty;
 $('sessions').replaceChildren();for(const session of s.sessions){const b=document.createElement('button');b.textContent=`${session.alive?'●':'○'} ${session.name} · ${session.agent} · ${session.status??'unknown'}`;b.className=s.draft.sessionId===session.id?'active':'';b.disabled=!session.alive;b.onclick=safe(async()=>{await call('select-session',session.id);selected=session.id;term.reset();term.write(await call('terminal-output',session.id));$('terminal-title').textContent=session.name;fit.fit();});$('sessions').append(b);}}
api.on('state',s=>{render(s);renderExtras(s);});
$('command-form').onsubmit=safe(async e=>{e.preventDefault();await call('text',$('command').value);$('command').value='';});
for(const b of document.querySelectorAll('[data-command]'))b.onclick=safe(()=>call('text',b.dataset.command));
$('launch').onsubmit=safe(async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.enhanced=e.target.elements.enhanced.checked;const session=await call('launch-session',data);selected=session.id;term.reset();term.write(await call('terminal-output',session.id));});
$('draft').oninput=()=>{dirty=true;$('submit-draft').disabled=true;};
$('save-draft').onclick=safe(async()=>{await call('draft-update',{text:$('draft').value,revision:editRevision});dirty=false;render(await call('state'));});
$('reload-draft').onclick=safe(async()=>{dirty=false;render(await call('state'));});
$('clear-draft').onclick=safe(async()=>{await call('draft-update',{text:'',revision:state.draft.revision});dirty=false;render(await call('state'));});
$('submit-draft').onclick=safe(async()=>{await call('draft-submit',{id:crypto.randomUUID(),sessionId:state.draft.sessionId,revision:state.draft.revision});});
$('close-session').onclick=safe(async()=>{if(selected&&confirm('结束此会话？未完成的 agent 工作将中断。'))await call('close-session',selected);});
async function pairings(){$('pairings').replaceChildren();for(const p of await call('pairing')){const card=document.createElement('div'),img=document.createElement('img'),label=document.createElement('p'),copy=document.createElement('button');img.src=p.qr;img.alt='Qube 配对二维码';label.textContent=p.url;copy.textContent='复制配对数据';copy.onclick=safe(async()=>{await navigator.clipboard.writeText(p.payload);toast('已复制，可在手机手动粘贴配对');});card.append(img,label,copy);$('pairings').append(card);}}
$('refresh-pairing').onclick=safe(pairings);$('revoke-pairing').onclick=safe(async()=>{await call('revoke-pairing');await pairings();});
$('save-config').onclick=safe(async()=>{const c=JSON.parse($('config').value);await call('save-config',c);toast('设置已保存');});
$('speech-check').onclick=safe(async()=>toast(await call('speech-health')));$('unload-model').onclick=safe(async()=>{await call('speech-unload');toast('语音模型已释放');});
(async()=>{render(await call('state'));$('config').value=JSON.stringify(await call('config'),null,2);})().catch(()=>{});

function feature(action,extra={}){return call('feature',{action,revision:state?.draft.revision,...extra});}
for(const b of document.querySelectorAll('[data-feature]'))b.onclick=safe(()=>feature(b.dataset.feature));
$('capture').onclick=safe(()=>feature('capture',{target:$('capture-window').value||undefined}));
$('refresh-windows').onclick=safe(async()=>{$('capture-window').replaceChildren();for(const w of await call('windows')){const o=document.createElement('option');o.value=w.id;o.textContent=w.name;$('capture-window').append(o);}});
$('explain').onclick=safe(()=>feature('helper',{target:'selection',text:'用中文解释以下文本'}));
$('translate').onclick=safe(()=>feature('helper',{target:'clipboard',text:'外文翻译成中文，中文翻译成英文，只返回译文'}));
$('rewrite-draft').onclick=safe(()=>feature('helper',{target:'draft',text:($('rewrite-instruction').value||'整理成清晰的需求')+'。只返回修改后的完整草稿。'}));
$('clear-history').onclick=safe(async()=>{if(confirm('清空电脑操作历史？'))await feature('clear-history');});
$('history-filter').oninput=()=>renderExtras(state);
let metricsTimer; $('metrics-live').onchange=()=>{clearInterval(metricsTimer);if($('metrics-live').checked)metricsTimer=setInterval(()=>{if(!$('companion').classList.contains('hidden'))feature('metrics').catch(()=>{});},2000);};
async function projects(){const c=await call('config');$('project-list').replaceChildren();for(const p of c.projects??[]){const o=document.createElement('option');o.value=p.name;o.textContent=p.name;o.selected=p.name===c.activeProject;$('project-list').append(o);}}
$('choose-project').onclick=safe(async()=>{const c=await call('config');c.activeProject=$('project-list').value;await call('save-config',c);});
$('project-form').onsubmit=safe(async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target)),c=await call('config');c.projects=[...(c.projects??[]).filter(x=>x.name!==p.name),p];c.activeProject=p.name;await call('save-config',c);$('config').value=JSON.stringify(c,null,2);await projects();toast('项目已保存');});
$('recover-draft').onclick=safe(()=>feature('recover-draft',{target:$('saved-drafts').value}));
function renderExtras(s){if(!s)return;
 $('saved-drafts').replaceChildren();for(const d of s.savedDrafts??[]){const o=document.createElement('option');o.value=d.id;o.textContent=d.preview||`${d.images} 张图片`;$('saved-drafts').append(o);}
 $('attachments').replaceChildren();for(const a of s.draft.attachments??[]){const box=document.createElement('div'),img=document.createElement('img'),name=document.createElement('p'),remove=document.createElement('button');img.src=a.preview;img.alt=a.name;img.style.width='220px';name.textContent=a.name;remove.textContent='移除';remove.onclick=safe(()=>feature('remove-attachment',{target:a.id}));box.append(img,name,remove);$('attachments').append(box);}
 $('helper-state').textContent=s.helper?.running?'辅助会话处理中…':'';$('helper-result').textContent=s.helper?.result??'';$('rewrite-preview').textContent=s.rewrite?'修改前：\n'+s.rewrite.before+'\n修改后：\n'+s.rewrite.text:'';
 $('scene-progress').textContent=s.scene?`${s.scene.name} · ${s.scene.status}\n`+s.scene.steps.map(x=>`${x.name}：${x.status}${x.error?' · '+x.error:''}`).join('\n'):'';
 const m=s.metrics;$('metrics').textContent=m?`采样时间：${new Date(m.at).toLocaleTimeString()}\nCPU：${m.cpu?.toFixed(1)??'不可用'}%\n内存：${(m.memory.used/1073741824).toFixed(1)} / ${(m.memory.total/1073741824).toFixed(1)} GB\nCPU 温度：当前接口不支持\n${(m.gpu??[]).map((g,i)=>`GPU ${i}：${g.utilization??'不可用'}% · ${g.temperature??'不可用'}℃ · ${g.memoryUsedMB} / ${g.memoryTotalMB} MB`).join('\n')}\n${m.gpuError??''}\n内存占用前五：\n${m.processes.map(p=>`${p.name} ${(p.bytes/1048576).toFixed(0)} MB`).join('\n')}`:'尚无采样';
 $('history').replaceChildren();for(const e of (s.history??[]).filter(e=>JSON.stringify(e).includes($('history-filter').value))){const row=document.createElement('p');row.textContent=`${new Date(e.at).toLocaleString()} · ${e.action} · ${e.status} · ${e.message} ${e.target?'→ '+e.target:''}`;$('history').append(row);}
 const fingerprint=JSON.stringify(s.approvals??[]);if($('approvals').dataset.fingerprint!==fingerprint){$('approvals').dataset.fingerprint=fingerprint;$('approvals').replaceChildren();for(const r of s.approvals??[]){const box=document.createElement('article'),label=document.createElement('pre');label.textContent=r.method+'\n'+JSON.stringify(r.params,null,2);box.append(label);if(r.method==='item/tool/requestUserInput'){const inputs=[];for(const q of r.params.questions??[]){const label=document.createElement('label'),input=document.createElement('input');label.textContent=q.question+' '+(q.options??[]).map(o=>o.label).join(' / ');label.append(input);box.append(label);inputs.push([q.id,input]);}const send=document.createElement('button');send.textContent='提交回答';send.onclick=safe(()=>call('approval',{sessionId:r.sessionId,key:r.key,answer:{answers:Object.fromEntries(inputs.map(([id,input])=>[id,{answers:[input.value]}]))}}));box.append(send);}else{for(const [answer,label] of [['accept','允许本次'],['decline','拒绝']]){const b=document.createElement('button');b.textContent=label;b.onclick=safe(()=>call('approval',{sessionId:r.sessionId,key:r.key,answer}));box.append(b);}}$('approvals').append(box);}}
}
projects().catch(()=>{});
